version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: urlshortener_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshort
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: urlshortener_api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/urlshort
      JWT_SECRET: supersecret
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client-app
      dockerfile: Dockerfile
    container_name: urlshortener_client
    depends_on:
      - server
    ports:
      - "3001:3001"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
    volumes:
      - ./client-app:/app
      - /app/node_modules

volumes:
  pgdata:
